In [47]:
import tensorflow as tf


image_data = tf.io.read_file("caisar.png")
image = tf.image.decode_image(image_data)
img_shape = 224
image = tf.image.resize(image,[img_shape,img_shape])

image = image[:, :, :3]


image

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[233.5201 , 232.5201 , 238.5201 ],
        [233.43973, 232.43973, 238.43973],
        [232.     , 231.     , 237.     ],
        ...,
        [219.20093, 217.20093, 228.20093],
        [219.43973, 217.43973, 228.43973],
        [218.35942, 217.3192 , 228.3192 ]],

       [[234.     , 233.     , 239.     ],
        [234.     , 233.     , 239.     ],
        [234.     , 233.     , 239.     ],
        ...,
        [218.     , 216.     , 227.     ],
        [217.98135, 215.98135, 226.98135],
        [217.9576 , 215.9576 , 226.9576 ]],

       [[235.21013, 234.21013, 240.21013],
        [235.17766, 234.17766, 240.17766],
        [234.     , 233.     , 239.     ],
        ...,
        [216.19197, 214.19197, 225.19197],
        [214.75224, 212.75224, 223.75224],
        [214.19197, 212.19197, 223.19197]],

       ...,

       [[237.5201 , 237.5201 , 238.11604],
        [238.     , 237.43973, 240.12053],
        [238.     , 237.   

In [48]:
image = tf.expand_dims(image,axis = 0)
image

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[233.5201 , 232.5201 , 238.5201 ],
         [233.43973, 232.43973, 238.43973],
         [232.     , 231.     , 237.     ],
         ...,
         [219.20093, 217.20093, 228.20093],
         [219.43973, 217.43973, 228.43973],
         [218.35942, 217.3192 , 228.3192 ]],

        [[234.     , 233.     , 239.     ],
         [234.     , 233.     , 239.     ],
         [234.     , 233.     , 239.     ],
         ...,
         [218.     , 216.     , 227.     ],
         [217.98135, 215.98135, 226.98135],
         [217.9576 , 215.9576 , 226.9576 ]],

        [[235.21013, 234.21013, 240.21013],
         [235.17766, 234.17766, 240.17766],
         [234.     , 233.     , 239.     ],
         ...,
         [216.19197, 214.19197, 225.19197],
         [214.75224, 212.75224, 223.75224],
         [214.19197, 212.19197, 223.19197]],

        ...,

        [[237.5201 , 237.5201 , 238.11604],
         [238.     , 237.43973, 240.12053],


In [37]:
from tensorflow.keras.models import load_model
#food101hope.save("/content/drive/Othercomputers/My Laptop/code/MacDeepL/food101/finaladvance07_efficientnetb0_fine_tuned_101_classes_augmentation/")
model = load_model("/content/drive/Othercomputers/My Laptop/code/MacDeepL/food101/07_efficientnetb0_fine_tuned_101_classes_mixed_precision")
model.summary()

Model: "model_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_layer (InputLayer)    [(None, 224, 224, 3)]     0         
                                                                 
 efficientnetv2-b0 (Functio  (None, None, None, 1280   5919312   
 nal)                        )                                   
                                                                 
 pooling_layer (GlobalAvera  (None, 1280)              0         
 gePooling2D)                                                    
                                                                 
 dense_15 (Dense)            (None, 101)               129381    
                                                                 
 softmax_float32 (Activatio  (None, 101)               0         
 n)                                                              
                                                          

In [32]:
food_categories = ["Apple pie", "Baby back ribs", "Baklava", "Beef carpaccio", "Beef tartare", "Beignets", "Bibimbap", "Bread pudding", "Breakfast burrito", "Bruschetta", "Caesar salad", "Cannoli", "Caprese salad", "Carrot cake", "Ceviche", "Cheese plate", "Cheesecake", "Chicken curry", "Chicken quesadilla", "Chicken wings", "Chocolate cake", "Chocolate mousse", "Churros", "Clam chowder", "Club sandwich", "Crab cakes", "Creme brulee", "Croque madame", "Cup cakes", "Deviled eggs", "Donuts", "Dumplings", "Edamame", "Eggs benedict", "Escargots", "Falafel", "Filet mignon", "Fish and chips", "Foie gras", "French fries", "French onion soup", "French toast", "Fried calamari", "Fried rice", "Frozen yogurt", "Garlic bread", "Gnocchi", "Greek salad", "Grilled cheese sandwich", "Grilled salmon", "Guacamole", "Gyoza", "Hamburger", "Hot and sour soup", "Hot dog", "Huevos rancheros", "Hummus", "Ice cream", "Lasagna", "Lobster bisque", "Lobster roll sandwich", "Macaroni and cheese", "Macarons", "Margarita", "Miso soup", "Mussels", "Nachos", "Omelette", "Onion rings", "Oysters", "Pad thai", "Paella", "Pancakes", "Panna cotta", "Peking duck", "Pho", "Pizza", "Pork chop", "Poutine", "Prime rib", "Pulled pork sandwich", "Ramen", "Ravioli", "Red velvet cake", "Risotto", "Sashimi", "Scallops", "Seaweed salad", "Shrimp and grits", "Shrimp scampi", "Spaghetti bolognese", "Spaghetti carbonara", "Spring rolls", "Steak", "Strawberry shortcake", "Sushi", "Tacos", "Takoyaki", "Tiramisu", "Tuna tartare", "Waffles"]

In [49]:
pred = model.predict(image)

pred_class_int = int(pred.argmax(axis=1))


1/1 [==============================] - 0s 156ms/step


In [50]:
pred_class_int

11

In [51]:
food_categories[pred_class_int]

'Cannoli'